/*
 * 文件名: FusionMessageType.java
 * 创建人: zhouyujun
 */
package com.theone.sns.common;

/**
 * 消息类型定义
 * 
 * @author zhouyujun
 */
public interface FusionMessageType {

	public interface AccountMessageType {

		int BASE = 0x10000000;

		int GET_VERIFY_CODE_SUCCESS = BASE + 1;

		int CHECK_VERIFY_CODE_AND_CREATE_ACCOUNT_SUCCESS = BASE + 2;

		int CREATE_EMAIL_ACCOUNT_SUCCESS = BASE + 3;

		int LOGIN_SUCCESS = BASE + 4;

		int CHECK_PASSWORD_SUCCESS = BASE + 5;

		int CHECK_PASSWORD_FAIL = BASE + 6;

		int UPDATE_PASSWORD_SUCCESS = BASE + 7;

		int GET_MYUSER_INFO_SUCCESS = BASE + 8;

		int UPDATE_MYUSER_INFO_SUCCESS = BASE + 9;

		int GET_MY_ALL_TAGS_SUCCESS = BASE + 10;

		int GET_VERIFY_CODE_FAIL = BASE + 11;

		int CHECK_VERIFY_CODE_AND_CREATE_ACCOUNT_FAIL = BASE + 12;

		int CREATE_EMAIL_ACCOUNT_FAIL = BASE + 13;

		int LOGIN_FAIL = BASE + 14;

		int LOGIN_SUCCESS_NEED_SET_USERINFO = BASE + 15;

		int UPDATE_MYUSER_INFO_FAIL = BASE + 16;

		int UPDATE_PASSWORD_FAIL = BASE + 17;

		int GET_MYUSER_INFO_FAIL = BASE + 18;

		int CHECK_VERIFY_CODE_SUCCESS = BASE + 19;

		int CHECK_VERIFY_CODE_FAIL = BASE + 20;

		int GET_MY_ALL_TAGS_FAIL = BASE + 21;

		int UPDATE_PRIVACY_INFO_SUCCESS = BASE + 22;

		int UPDATE_PRIVACY_INFO_FAIL = BASE + 23;

		int GET_REGISTER_INVITE_CODE_SUCCESS = BASE + 24;

		int GET_REGISTER_INVITE_CODE_FAIL = BASE + 25;

		int VERIFY_REGISTER_INVITE_CODE_SUCCESS = BASE + 26;

		int VERIFY_REGISTER_INVITE_CODE_FAIL = BASE + 27;

		int GET_INTEREST_SUCCESS = BASE + 28;

		int GET_INTEREST_FAIL = BASE + 29;

		int UPDATE_MY_CHARACTER_SUCCESS = BASE + 30;

		int UPDATE_MY_CHARACTER_FAIL = BASE + 31;

		int LOGIN_SUCCESS_NEED_SET_CHARACTER = BASE + 32;

		int EMAIL_RESET_PASSWORD_SUCCESS = BASE + 33;

		int EMAIL_RESET_PASSWORD_FAIL = BASE + 34;
	}

	public interface MBlogMessageType {

		int BASE = 0x20000000;

		int PULL_GET_MBLOG_LIST_SUCCESS = BASE + 1;

		int PUSH_GET_MBLOG_LIST_SUCCESS = BASE + 2;

		int UPDATE_MBLOG_FILTER_SUCCESS = BASE + 3;

		int GET_MBLOG_FILTER_SUCCESS = BASE + 4;

		int PUBLISH_MBLOG_SUCCESS = BASE + 5;

		int PULL_TAG_TO_GALLERY_SUCCESS = BASE + 6;

		int PUSH_TAG_TO_GALLERY_SUCCESS = BASE + 7;

		int TAG_TO_GALLERY_NOT_FOUND = BASE + 8;

		int GET_MBLOG_BY_ID_SUCCESS = BASE + 9;

		int GET_MBLOG_BY_ID_FAIL = BASE + 10;

		int DELETE_MBLOG_BY_ID_SUCCESS = BASE + 11;

		int DELETE_MBLOG_BY_ID_FAIL = BASE + 12;

		int PULL_GET_LIKES_LIST_SUCCESS = BASE + 13;

		int PUSH_GET_LIKES_LIST_SUCCESS = BASE + 14;

		int IS_LIKES_ACTION_SUCCESS = BASE + 15;

		int PULL_MBLOG_COMMENTS_LIST_SUCCESS = BASE + 16;

		int PUSH_MBLOG_COMMENTS_LIST_SUCCESS = BASE + 17;

		int PUBLISH_MBLOG_COMMENTS_SUCCESS = BASE + 18;

		int DELETE_MBLOG_COMMENTS_SUCCESS = BASE + 19;

		int GET_MBLOG_LIST_FROM_DB = BASE + 20;

		int GET_MBLOG_LIST_FAIL = BASE + 21;

		int UPDATE_MBLOG_FILTER_FAIL = BASE + 22;

		int PUBLISH_MBLOG_FAIL = BASE + 23;

		int GET_LIKES_LIST_FAIL = BASE + 24;

		int IS_LIKES_ACTION_FAIL = BASE + 25;

		int GET_MBLOG_COMMENTS_LIST_FAIL = BASE + 26;

		int PUBLISH_MBLOG_COMMENTS_FAIL = BASE + 27;

		int DELETE_MBLOG_COMMENTS_FAIL = BASE + 28;

		int PULL_FIND_GALLERY_SUCCESS = BASE + 29;

		int PUSH_FIND_GALLERY_SUCCESS = BASE + 30;

		int FIND_GALLERY_NOT_FOUND = BASE + 31;

		int PULL_SEARCH_GALLERY_SUCCESS = BASE + 32;

		int PUSH_SEARCH_GALLERY_SUCCESS = BASE + 33;

		int SEARCH_GALLERY_NOT_FOUND = BASE + 34;

		int PULL_SEARCH_USER_SUCCESS = BASE + 35;

		int PUSH_SEARCH_USER_SUCCESS = BASE + 36;

		int SEARCH_USER_NOT_FOUND = BASE + 37;

		int GET_GALLERY_LIST_FROM_DB = BASE + 38;

		int PULL_SEARCH_TAGS_SUCCESS = BASE + 39;

		int PUSH_SEARCH_TAGS_SUCCESS = BASE + 40;

		int SEARCH_TAGS_NOT_FOUND = BASE + 41;
		
		int DELETE_MBLOG_BY_ID = BASE + 42;
	}

	public interface UserMessageType {

		int BASE = 0x30000000;

		int PULL_USER_LIST_SUCCESS = BASE + 1;

		int PUSH_USER_LIST_SUCCESS = BASE + 2;

		int GET_RECOMMEND_USER_LIST_SUCCESS = BASE + 3;

		int PULL_SEARCH_USER_LIST_SUCCESS = BASE + 4;

		int PUSH_SEARCH_USER_LIST_SUCCESS = BASE + 5;

		int GET_MATCH_CONTACT_LIST_SUCCESS = BASE + 6;

		int GET_USER_BY_ID_SUCCESS = BASE + 7;

		int PULL_GALLERY_LIST_BY_ID_SUCCESS = BASE + 8;

		int PUSH_GALLERY_LIST_BY_ID_SUCCESS = BASE + 9;

		int PULL_MBLOG_LIST_BY_ID_SUCCESS = BASE + 10;

		int PUSH_MBLOG_LIST_BY_ID_SUCCESS = BASE + 11;

		int PULL_MENTIONEDGALLERY_LIST_BY_ID_SUCCESS = BASE + 12;

		int PUSH_MENTIONEDGALLERY_LIST_BY_ID_SUCCESS = BASE + 13;

		int PULL_TAGTHUMBNAILS_LIST_BY_ID_SUCCESS = BASE + 14;

		int PUSH_TAGTHUMBNAILS_LIST_BY_ID_SUCCESS = BASE + 15;

		int GET_ALIAS_BY_ID_SUCCESS = BASE + 16;

		int UPDATE_ALIAS_BY_ID_SUCCESS = BASE + 17;

		int PULL_RELATIONSHIPS_LIST_BY_ID_SUCCESS = BASE + 18;

		int PUSH_RELATIONSHIPS_LIST_BY_ID_SUCCESS = BASE + 19;

		int SET_RELATIONSHIP_BY_ID_SUCCESS = BASE + 20;

		int GET_USER_LIST_FROM_DB = BASE + 21;

		int GET_USER_LIST_FAIL = BASE + 22;

		int GET_RECOMMEND_USER_LIST_FAIL = BASE + 23;

		int GET_SEARCH_USER_LIST_FAIL = BASE + 24;

		int GET_MATCH_CONTACT_LIST_FAIL = BASE + 25;

		int GET_USER_BY_ID_FAIL = BASE + 26;

		int GET_GALLERY_LIST_BY_ID_FAIL = BASE + 27;

		int PUSH_MBLOG_LIST_BY_ID_FAIL = BASE + 28;

		int GET_MENTIONEDGALLERY_LIST_BY_ID_FAIL = BASE + 29;

		int GET_TAGTHUMBNAILS_LIST_BY_ID_FAIL = BASE + 30;

		int GET_NOTENAME_BY_ID_FAIL = BASE + 31;

		int UPDATE_ALIAS_BY_ID_FAIL = BASE + 32;

		int GET_RELATIONSHIPS_LIST_BY_ID_FAIL = BASE + 33;

		int SET_RELATIONSHIP_BY_ID_FAIL = BASE + 34;

		int PULL_MBLOG_LIST_BY_ID_AND_TAG_SUCCESS = BASE + 35;

		int PUSH_MBLOG_LIST_BY_ID_AND_TAG_SUCCESS = BASE + 36;

		int GET_MBLOG_LIST_BY_ID__AND_TAG_FAIL = BASE + 37;

		int PULL_CIRCLE_SEARCH_SUCCESS = BASE + 38;

		int PUSH_CIRCLE_SEARCH_SUCCESS = BASE + 39;

		int CIRCLE_SEARCH_FAIL = BASE + 40;
		
		int CIRCLE_SEARCH_SUCCESS = BASE + 41;
	}

	public interface ChatMessageType {

		int BASE = 0x40000000;

		int SYNC_ALL_GROUP_SUCCESS = BASE + 1;

		int SYNC_ALL_GROUP_FAIL = BASE + 2;

		int CREATE_GROUP_SUCCESS = BASE + 3;

		int CREATE_GROUP_FAIL = BASE + 4;

		int UPDATE_GROUP_NAME_SUCCESS = BASE + 5;

		int UPDATE_GROUP_NAME_FAIL = BASE + 6;

		int UPDATE_MEMBER_GROUP_INFO_SUCCESS = BASE + 7;

		int UPDATE_MEMBER_GROUP_INFO_FAIL = BASE + 8;

		int GET_MESSAGE_LIST_FROM_DB = BASE + 9;

		int GET_JOINED_GROUP_LIST_FROM_DB = BASE + 10;

		int GET_UNJOINED_GROUP_LIST_FROM_DB = BASE + 11;

		int GET_CHAT_GROUP_FROM_DB = BASE + 12;

		int PULL_NOTIFY_ME_LIST_SUCCESS = BASE + 13;

		int PUSH_NOTIFY_ME_LIST_SUCCESS = BASE + 14;

		int GET_NOTIFY_ME_LIST_FAIL = BASE + 15;

		int GET_ALL_UNREAD_MESSAGE_COUNT = BASE + 16;

		int DELETE_UNJOINED_GROUP_SUCCESS = BASE + 17;

		int DELETE_UNJOINED_GROUP_FAIL = BASE + 18;

		int SEARCH_CHAT_FROM_DB = BASE + 19;

		int GET_PHOTO_MESSAGE_LIST_FROM_DB = BASE + 20;
	}
}
